// <auto-generated />
using System;
using Literatea.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Literatea.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200412070826_Inicio")]
    partial class Inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Literatea.Web.Data.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BookDetailId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("BookDetailId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Literatea.Web.Data.Entities.BookDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AutorName");

                    b.Property<string>("BookName");

                    b.Property<string>("Editorial");

                    b.Property<string>("Gender");

                    b.Property<int>("NumberPages");

                    b.HasKey("Id");

                    b.ToTable("BookDetails");
                });

            modelBuilder.Entity("Literatea.Web.Data.Entities.Forum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ForumDetailId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ForumDetailId");

                    b.ToTable("Forums");
                });

            modelBuilder.Entity("Literatea.Web.Data.Entities.ForumDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ForumName");

                    b.HasKey("Id");

                    b.ToTable("ForumDetails");
                });

            modelBuilder.Entity("Literatea.Web.Data.Entities.readerUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthdate");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<int?>("RoomId");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("readerUsers");
                });

            modelBuilder.Entity("Literatea.Web.Data.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BookId");

                    b.Property<int?>("ForumId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("ForumId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Literatea.Web.Data.Entities.Book", b =>
                {
                    b.HasOne("Literatea.Web.Data.Entities.BookDetail", "BookDetail")
                        .WithMany("Books")
                        .HasForeignKey("BookDetailId");
                });

            modelBuilder.Entity("Literatea.Web.Data.Entities.Forum", b =>
                {
                    b.HasOne("Literatea.Web.Data.Entities.ForumDetail")
                        .WithMany("Forums")
                        .HasForeignKey("ForumDetailId");
                });

            modelBuilder.Entity("Literatea.Web.Data.Entities.readerUser", b =>
                {
                    b.HasOne("Literatea.Web.Data.Entities.Room", "Room")
                        .WithMany("ReaderUsers")
                        .HasForeignKey("RoomId");
                });

            modelBuilder.Entity("Literatea.Web.Data.Entities.Room", b =>
                {
                    b.HasOne("Literatea.Web.Data.Entities.Book", "Book")
                        .WithMany("Rooms")
                        .HasForeignKey("BookId");

                    b.HasOne("Literatea.Web.Data.Entities.Forum", "Forum")
                        .WithMany("Rooms")
                        .HasForeignKey("ForumId");
                });
#pragma warning restore 612, 618
        }
    }
}
